name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run maven test
      uses: xlui/action-maven-cli/jdk11@master
      id: test
      with:
        lifecycle: 'clean package test'
